{% set name = "de-tagesschau" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1744af05d35b7eded4e9a1f638a42305b5e7b7a55520f6fe863df121f4a52b25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

test:
  imports:
    - deutschland.tagesschau
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bundesAPI/tagesschau-api
  summary: Tagesschau API
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
